from app.models.schemas import CostEstimationResult, CostItem, FundingAdvisorResult, FundingOption, StartupAnalysisRequest

def run_cost_and_funding_advisor(request: StartupAnalysisRequest) -> tuple[CostEstimationResult, FundingAdvisorResult]:
    """
    Agent 6: Cost Estimation & Funding Advisor Agent
    Calculates operational costs, budget gap, unit economics, and recommends bootstrap/grant/investor paths.
    """
    avail_budget = request.founder.available_budget or 100000.0
    
    # Cost Breakdown Estimation
    cost_items = [
        CostItem(
            category="MVP Software & Cloud Infrastructure",
            estimated_cost=25000.0,
            frequency="one-time",
            description="Domain, server hosting, API integrations, and developer tooling."
        ),
        CostItem(
            category="Regional Operations & Warehouse/Office Setup",
            estimated_cost=30000.0,
            frequency="one-time",
            description="Lease security, initial inventory/machinery, and regional hub setup."
        ),
        CostItem(
            category="Initial Growth Marketing & Launch Ads",
            estimated_cost=20000.0,
            frequency="monthly",
            description="Targeted social ads, local campus ambassador network, and content creation."
        )
    ]
    
    total_initial = sum(item.estimated_cost for item in cost_items)
    monthly_burn = 25000.0
    budget_gap = max(0.0, total_initial - avail_budget)
    
    cost_result = CostEstimationResult(
        total_initial_budget_required=total_initial,
        monthly_burn_rate=monthly_burn,
        cost_breakdown=cost_items,
        budget_gap=budget_gap,
        unit_economics_summary="Positive Contribution Margin: Estimated Cost per Unit ₹42 vs Average Order Selling Price ₹120 (Gross Margin ~65%)."
    )
    
    # Funding Strategy Logic
    bootstrap_feasible = avail_budget >= total_initial * 0.7
    
    primary_advice = (
        "Bootstrap your initial MVP using available funds and regional price arbitrage savings. Apply to University/State Incubators for non-dilutive seed grants."
        if bootstrap_feasible else
        f"Initial budget gap of ₹{budget_gap:,.0f} detected. Build a lean prototype for under ₹30,000, launch early to prove traction, then apply for MSME Startup Grants & Angel Seed Funding."
    )
    
    funding_options = [
        FundingOption(
            method="Bootstrapping & Cash Flow Reinvestment",
            suitability_score=9.2,
            why_suitable="Retains 100% equity ownership while validating unit economics and customer demand.",
            actionable_steps=[
                "Keep fixed operating overhead low by operating out of cost-effective regional hubs (e.g. Noida).",
                "Reinvest early product revenue directly into digital marketing."
            ]
        ),
        FundingOption(
            method="Government MSME & University Incubator Grants",
            suitability_score=8.8,
            why_suitable="Provides ₹2 Lakhs - ₹10 Lakhs non-dilutive grant capital for early stage ventures.",
            actionable_steps=[
                "Register on Startup India / State MSME Portal.",
                "Apply to college incubator pitch competitions with the generated pitch deck."
            ]
        ),
        FundingOption(
            method="Angel Investors & Pre-Seed Syndicates",
            suitability_score=7.5,
            why_suitable="Accelerates growth once initial 100 paying customers or recurring metrics are demonstrated.",
            actionable_steps=[
                "Prepare 10-slide pitch deck (auto-generated by StartupPilot AI).",
                "Target micro-VCs and angel syndicates focused on early-stage tech/regional ventures."
            ]
        )
    ]
    
    funding_result = FundingAdvisorResult(
        primary_recommendation=primary_advice,
        bootstrap_feasible=bootstrap_feasible,
        incubator_or_grant_opportunities=[
            "Startup India Seed Fund Scheme (SISFS)",
            "State MSME Technology Innovation Grant",
            "University Entrepreneurship Cell Incubation Fund"
        ],
        loan_advisability="Avoid bank loans at idea stage. Re-evaluate credit/loan options only after achieving steady monthly revenue.",
        investor_timeline_recommendation="Seek Angel/Pre-Seed investment between Months 4-6 after proving initial traction.",
        options=funding_options
    )
    
    return cost_result, funding_result
